### ISSUE TITLE
Ubuntu Repository Instructions - SSL Error

### ISSUE THREAD

**Issue by markwallsgrove** [regolith-linux/regolith-desktop-website#11]
The following instructions for installing on Ubuntu fails due to a SSL error:
https://github.com/regolith-linux/regolith-desktop-website/blob/ad83e6b0892c8bc248a26622c5c234f328fb2441/static/install-release-ubuntu-22.04-amd64.txt#L2

Changing the `https://regolith-desktop.io` to `https://regolith-desktop.org` fixes the issue. 

![image](https://user-images.githubusercontent.com/6328824/180170274-a138dc05-2dae-4ca5-80e9-1c438637972a.png)

**Comment by fwarmuth** [comment]
Hey,
its the certificate which expired a month ago. I guess the maintainer is on vacation?
Cheers

**Comment by kgilmer** [comment]
All cert issues should be resolved now.  All package URLs should be `regolith-desktop.org`.  Kindly re-open if any problems persist.
