### ISSUE TITLE
sway migration guide, regolith-session-wayland nonexisting package

### ISSUE THREAD

**Issue by wagneja4** [regolith-linux/regolith-desktop-website#24]
On the site https://regolith-desktop.com/docs/howtos/install-sway/ it says for sway support, you should install `regolith-session-wayland`, but in the repo there is only `regolith-session-sway`

**Comment by kgilmer** [comment]
Whoops, yes someone else saw that and I just applied their fix ~ https://github.com/regolith-linux/regolith-desktop-website/pull/23
