### ISSUE TITLE
Can't install `regolith-session-sway`, `sway-regolith` not found in 23.04 testing sources

### ISSUE THREAD

**Issue by Sturgelose** [regolith-linux/regolith-desktop-website#26]
Following the docs in https://regolith-desktop.com/docs/reference/Releases/regolith-3.0-release-notes/ and https://regolith-desktop.com/docs/howtos/install-sway/, if I try to install the `regolith-session-sway` in Ubuntu 23.04, using the `testing` and `lunar` apt deb sources, the package cannot be installed because `sway-regolith` does not exist:

```shell
❯ sudo apt install regolith-session-sway
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 regolith-session-sway : Depends: sway-regolith but it is not installable
E: Unable to correct problems, you have held broken packages.

```

If I try to install the package directly:

```shell
❯ sudo apt install sway-regolith
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package sway-regolith is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'sway-regolith' has no installation candidate
```

Maybe this package does not exist yet in 23.04 somehow?

**Comment by kgilmer** [comment]
Thanks for the detailed bug report @Sturgelose .  Yes you found a problem, I'll update this thread when I've tested the fix.

**Comment by Sturgelose** [comment]
Just testing while you wrote the commment and I can verify it works now!

So thanks a lot!

I've found a couple of limitations/bugs in regolith sway such as:

* Can't share screen in chrome nor firefox
* `regolith-control-center` does not allow any changes: Can't change screen placement, percentage and name of screens is not right (totally different name from Ubuntu Wayland)

Which is the best place to report them? I'd like to avoid spamming (and also check if those are already reported/tracked somewhere)

Kudos!

**Comment by kgilmer** [comment]
Please file issues in the [`regolith-desktop` repo](https://github.com/regolith-linux/regolith-desktop/issues), and mention that you're testing the sway session, thanks!
