### ISSUE TITLE
no such file or directory: package.json 

### ISSUE THREAD

**Issue by junghan0611** [regolith-linux/regolith-desktop-website#4]
Hi, I'm new user from South Korea. 

`npm install` turn out no package.json file is in .gitignore.

Regolith is amazing project for tiling WM beginners like me. 
** installed on Ubuntu 22.04 Desktop **

**Comment by kgilmer** [comment]
Hi @junghan0611 , glad you are enjoying Regolith.  Maybe I misunderstand your concern, but I do see that file in the `.gitignore` file..  https://github.com/regolith-linux/regolith-desktop-website/blob/main/.gitignore#L6

**Comment by junghan0611** [comment]
Thanks! :-)
