### ISSUE TITLE
Reference > Config Files needs updating for Regolith 2

### ISSUE THREAD

**Issue by mfisher87** [regolith-linux/regolith-desktop-website#5]
https://regolith-desktop.com/docs/reference/configurations/

The page above contains a mix of regolith/regolith2 paths.

Discovered by user `@Chris` on Slack: https://regolith-linux.slack.com/archives/CLM0Y3H5Y/p1656926353257609

I'll try and make some time to open a PR!

**Comment by mfisher87** [comment]
Resolved in PR #6 !

**Comment by kgilmer** [comment]
Closing since PR is merged
